# Generated by Django 5.0.2 on 2024-03-03 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.TextField(null=True),
        ),
    ]
