# Generated by Django 5.0.2 on 2024-03-04 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0004_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='age',
        ),
        migrations.AddField(
            model_name='car',
            name='car_age',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='car',
            name='car_name',
            field=models.CharField(default=10, max_length=100),
        ),
    ]
